version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_webtest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 112002
      POSTGRES_DB: webtest
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
